export const initialData: Sheet = {
	language: 'en',
	edition: '7E',
	era: '20s',
	//
	name: '',
	player: '',
	occupation: '',
	age: null,
	sex: '',
	residence: '',
	birthplace: '',
	//
	characteristics: {
		STR: null,
		DEX: null,
		POW: null,
		CON: null,
		APP: null,
		EDU: null,
		SIZ: null,
		INT: null,
		MOV: null,
		MOVPlus: null,
		MOVMinus: null,
	},
	//
	currentHP: null,
	maxHP: null,
	currentMP: null,
	maxMP: null,
	startLUCK: null,
	LUCK: null,
	insaneSAN: null,
	startSAN: null,
	currentSAN: null,
	maxSAN: null,
	//
	portraitURL: '',
	//
	isTemporaryInsanity: false,
	isIndefiniteInsanity: false,
	isMajorWound: false,
	isUnconscious: false,
	isDying: false,
	//
	skills: {
		accounting: { name: 'Accounting', value: null, isSuccess: false, initValue: 5 },
		anthropology: { name: 'Anthropology', value: null, isSuccess: false, initValue: 1 },
		appraise: { name: 'Appraise', value: null, isSuccess: false, initValue: 5 },
		archaeology: { name: 'Archaeology', value: null, isSuccess: false, initValue: 1 },
		art: { name: 'Art', value: null, isSuccess: false, initValue: 5 },
		charm: { name: 'Charm', value: null, isSuccess: false, initValue: 15 },
		climb: { name: 'Climb', value: null, isSuccess: false, initValue: 20 },
		creditRating: { name: 'Credit Rating', value: null, isSuccess: false, initValue: 0 },
		cthulhuMythos: { name: 'Cthulhu Mythos', value: null, isSuccess: false, initValue: 0 },
		disguise: { name: 'Disguise', value: null, isSuccess: false, initValue: 5 },
		dodge: { name: 'Dodge', value: null, isSuccess: false, initValue: 0 },
		driveAuto: { name: 'Drive Auto', value: null, isSuccess: false, initValue: 20 },
		electricalRepair: { name: 'Electrical Repair', value: null, isSuccess: false, initValue: 10 },
		fastTalk: { name: 'Fast Talk', value: null, isSuccess: false, initValue: 5 },
		fightingBrawl: { name: 'Fighting (Brawl)', value: null, isSuccess: false, initValue: 25 },
		firearmsHandgun: { name: 'Firearms (Handgun)', value: null, isSuccess: false, initValue: 20 },
		firearmsRifle: {
			name: 'Firearms (Rifle/Shotgun)',
			value: null,
			isSuccess: false,
			initValue: 25,
		},
		firstAid: { name: 'First Aid', value: null, isSuccess: false, initValue: 30 },
		history: { name: 'History', value: null, isSuccess: false, initValue: 5 },
		intimidate: { name: 'Intimidate', value: null, isSuccess: false, initValue: 15 },
		jump: { name: 'Jump', value: null, isSuccess: false, initValue: 20 },
		languageOwn: { name: 'Language (Own)', value: null, isSuccess: false, initValue: 0 },
		languageOther: { name: 'Language (Other)', value: null, isSuccess: false, initValue: 1 },
		law: { name: 'Law', value: null, isSuccess: false, initValue: 5 },
		libraryUse: { name: 'Library Use', value: null, isSuccess: false, initValue: 20 },
		listen: { name: 'Listen', value: null, isSuccess: false, initValue: 20 },
		locksmith: { name: 'Locksmith', value: null, isSuccess: false, initValue: 1 },
		mechanicalRepair: { name: 'Mechanical Repair', value: null, isSuccess: false, initValue: 10 },
		medicine: { name: 'Medicine', value: null, isSuccess: false, initValue: 1 },
		naturalWorld: { name: 'Natural World', value: null, isSuccess: false, initValue: 10 },
		navigate: { name: 'Navigate', value: null, isSuccess: false, initValue: 10 },
		occult: { name: 'Occult', value: null, isSuccess: false, initValue: 5 },
		operateHeavyMachinery: { name: 'Op. Hv. Machine', value: null, isSuccess: false, initValue: 1 },
		persuade: { name: 'Persuade', value: null, isSuccess: false, initValue: 10 },
		pilot: { name: 'Pilot', value: null, isSuccess: false, initValue: 1 },
		psychoanalysis: { name: 'Psychoanalysis', value: null, isSuccess: false, initValue: 1 },
		psychology: { name: 'Psychology', value: null, isSuccess: false, initValue: 10 },
		ride: { name: 'Ride', value: null, isSuccess: false, initValue: 5 },
		science: { name: 'Science', value: null, isSuccess: false, initValue: 1 },
		sleightOfHand: { name: 'Sleight of Hand', value: null, isSuccess: false, initValue: 10 },
		spotHidden: { name: 'Spot Hidden', value: null, isSuccess: false, initValue: 25 },
		stealth: { name: 'Stealth', value: null, isSuccess: false, initValue: 20 },
		survival: { name: 'Survival', value: null, isSuccess: false, initValue: 10 },
		swim: { name: 'Swim', value: null, isSuccess: false, initValue: 20 },
		throw: { name: 'Throw', value: null, isSuccess: false, initValue: 20 },
		track: { name: 'Track', value: null, isSuccess: false, initValue: 10 },
	},
	weapons: [
		{
			weapon: 'unarmed',
			skill: null,
			damage: '1d3+db',
			range: null,
			numberOfAttacks: 1,
			ammo: null,
			malfunction: false,
		},
	],
	combat: {
		damageBonus: null,
		build: null,
	},
	myStory: '',
	backstory: {
		personalDescription: '',
		traits: '',
		ideologyAndBeliefs: '',
		injuriesAndScars: '',
		significantPeople: '',
		phobiasAndManias: '',
		meaningfulLocations: '',
		arcaneTomesSpellsAndArtifacts: '',
		treasuredPossessions: '',
		encountersWithStrangeEntities: '',
	},
	gearAndPossessions: '',
	wealth: {
		spendingLevel: '',
		cash: '',
		assets: '',
	},
	fellowInvestigators: [],
	note: '',
}
