export const initialData: Sheet = {
	language: 'en',
	edition: '7E',
	era: '20s',
	//
	name: '',
	player: '',
	occupation: '',
	age: null,
	sex: '',
	residence: '',
	birthplace: '',
	//
	characteristics: {
		STR: null,
		DEX: null,
		POW: null,
		CON: null,
		APP: null,
		EDU: null,
		SIZ: null,
		INT: null,
		MOV: null,
		MOVPlus: null,
		MOVMinus: null,
	},
	//
	currentHP: null,
	maxHP: null,
	currentMP: null,
	maxMP: null,
	startLUCK: null,
	LUCK: null,
	insaneSAN: null,
	startSAN: null,
	currentSAN: null,
	maxSAN: null,
	//
	portraitURL: '',
	//
	isTemporaryInsanity: false,
	isIndefiniteInsanity: false,
	isMajorWound: false,
	isUnconscious: false,
	isDying: false,
	//
	skillMemo: '',
	skills: {
		accounting: { isEditable: false, name: 'Accounting', value: 0, initValue: 5, isSuccess: false },
		anthropology: {
			isEditable: false,
			name: 'Anthropology',
			value: 0,
			initValue: 1,
			isSuccess: false,
		},
		appraise: { isEditable: false, name: 'Appraise', value: 0, initValue: 5, isSuccess: false },
		archaeology: {
			isEditable: false,
			name: 'Archaeology',
			value: 0,
			initValue: 1,
			isSuccess: false,
		},
		'art/craft': { isEditable: true, name: 'Art/Craft', value: 0, initValue: 5, isSuccess: false },
		charm: { isEditable: false, name: 'Charm', value: 0, initValue: 15, isSuccess: false },
		climb: { isEditable: false, name: 'Climb', value: 0, initValue: 20, isSuccess: false },
		creditRating: {
			isEditable: false,
			name: 'Credit Rating',
			value: 0,
			initValue: 0,
			isSuccess: false,
		},
		cthulhuMythos: {
			isEditable: false,
			name: 'Cthulhu Mythos',
			value: 0,
			initValue: 0,
			isSuccess: false,
		},
		disguise: { isEditable: false, name: 'Disguise', value: 0, initValue: 5, isSuccess: false },
		dodge: { isEditable: false, name: 'Dodge', value: 0, initValue: 'DEX/2', isSuccess: false },
		driveAuto: { isEditable: false, name: 'Drive Auto', value: 0, initValue: 20, isSuccess: false },
		electricalRepair: {
			isEditable: false,
			name: 'Electrical Repair',
			value: 0,
			initValue: 10,
			isSuccess: false,
		},
		fastTalk: { isEditable: false, name: 'Fast Talk', value: 0, initValue: 5, isSuccess: false },
		fightingBrawl: {
			isEditable: false,
			name: 'Fighting (Brawl)',
			value: 0,
			initValue: 25,
			isSuccess: false,
		},
		fighting: { isEditable: true, name: 'Fighting', value: 0, initValue: 0, isSuccess: false },
		firearmsHandgun: {
			isEditable: false,
			name: 'Firearms (Handgun)',
			value: 0,
			initValue: 20,
			isSuccess: false,
		},
		firearmsRifle: {
			isEditable: false,
			name: 'Firearms (Rifle/Shotgun)',
			value: 0,
			initValue: 25,
			isSuccess: false,
		},
		firearms: { isEditable: true, name: 'Firearms', value: 0, initValue: 0, isSuccess: false },
		firstAid: { isEditable: false, name: 'First Aid', value: 0, initValue: 30, isSuccess: false },
		history: { isEditable: false, name: 'History', value: 0, initValue: 5, isSuccess: false },
		intimidate: {
			isEditable: false,
			name: 'Intimidate',
			value: 0,
			initValue: 15,
			isSuccess: false,
		},
		jump: { isEditable: false, name: 'Jump', value: 0, initValue: 20, isSuccess: false },
		languageOwn: {
			isEditable: true,
			name: 'Language Own',
			value: 0,
			initValue: 'EDU',
			isSuccess: false,
		},
		languageOther: {
			isEditable: true,
			name: 'Language Other',
			value: 0,
			initValue: 1,
			isSuccess: false,
		},
		law: { isEditable: false, name: 'Law', value: 0, initValue: 5, isSuccess: false },
		libraryUse: {
			isEditable: false,
			name: 'Library Use',
			value: 0,
			initValue: 20,
			isSuccess: false,
		},
		listen: { isEditable: false, name: 'Listen', value: 0, initValue: 20, isSuccess: false },
		locksmith: { isEditable: false, name: 'Locksmith', value: 0, initValue: 1, isSuccess: false },
		mechanicalRepair: {
			isEditable: false,
			name: 'Mechanical Repair',
			value: 0,
			initValue: 10,
			isSuccess: false,
		},
		medicine: { isEditable: false, name: 'Medicine', value: 0, initValue: 1, isSuccess: false },
		naturalWorld: {
			isEditable: false,
			name: 'Natural World',
			value: 0,
			initValue: 10,
			isSuccess: false,
		},
		navigate: { isEditable: false, name: 'Navigate', value: 0, initValue: 10, isSuccess: false },
		occult: { isEditable: false, name: 'Occult', value: 0, initValue: 5, isSuccess: false },
		persuade: { isEditable: false, name: 'Persuade', value: 0, initValue: 10, isSuccess: false },
		pilot: { isEditable: true, name: 'Pilot', value: 0, initValue: 1, isSuccess: false },
		psychoanalysis: {
			isEditable: false,
			name: 'Psychoanalysis',
			value: 0,
			initValue: 1,
			isSuccess: false,
		},
		psychology: {
			isEditable: false,
			name: 'Psychology',
			value: 0,
			initValue: 10,
			isSuccess: false,
		},
		ride: { isEditable: false, name: 'Ride', value: 0, initValue: 5, isSuccess: false },
		science: { isEditable: true, name: 'Science', value: 0, initValue: 1, isSuccess: false },
		sleightOfHand: {
			isEditable: false,
			name: 'Sleight of Hand',
			value: 0,
			initValue: 10,
			isSuccess: false,
		},
		spotHidden: {
			isEditable: false,
			name: 'Spot Hidden',
			value: 0,
			initValue: 25,
			isSuccess: false,
		},
		stealth: { isEditable: false, name: 'Stealth', value: 0, initValue: 20, isSuccess: false },
		survival: { isEditable: true, name: 'Survival', value: 0, initValue: 10, isSuccess: false },
		swim: { isEditable: false, name: 'Swim', value: 0, initValue: 20, isSuccess: false },
		throw: { isEditable: false, name: 'Throw', value: 0, initValue: 20, isSuccess: false },
		track: { isEditable: false, name: 'Track', value: 0, initValue: 10, isSuccess: false },
	},
	weapons: [
		{
			name: 'unarmed',
			isEditable: false,
			skill: null,
			damage: '1d3+db',
			range: null,
			numberOfAttacks: 1,
			ammo: null,
			malfunction: false,
		},
	],
	combat: {
		damageBonus: null,
		build: null,
	},
	myStory: '',
	backstory: {
		personalDescription: '',
		traits: '',
		ideologyAndBeliefs: '',
		injuriesAndScars: '',
		significantPeople: '',
		phobiasAndManias: '',
		meaningfulLocations: '',
		arcaneTomesSpellsAndArtifacts: '',
		treasuredPossessions: '',
		encountersWithStrangeEntities: '',
	},
	gearAndPossessions: '',
	wealth: {
		spendingLevel: '',
		cash: '',
		assets: '',
	},
	fellowInvestigators: [],
	note: '',
}
