export const initialData: Sheet = {
	language: 'en',
	edition: '7E',
	era: '20s',
	//
	name: '',
	player: '',
	occupation: '',
	age: null,
	sex: '',
	residence: '',
	birthplace: '',
	//
	characteristics: {
		STR: null,
		DEX: null,
		POW: null,
		CON: null,
		APP: null,
		EDU: null,
		SIZ: null,
		INT: null,
		MOV: null,
		MOVPlus: null,
		MOVMinus: null,
	},
	//
	currentHP: null,
	maxHP: null,
	currentMP: null,
	maxMP: null,
	startLUCK: null,
	LUCK: null,
	insaneSAN: null,
	startSAN: null,
	currentSAN: null,
	maxSAN: null,
	//
	portraitURL: '',
	//
	isTemporaryInsanity: false,
	isIndefiniteInsanity: false,
	isMajorWound: false,
	isUnconscious: false,
	isDying: false,
	//
	skills: {
		accounting: {
			isEditable: false,
			name: 'Accounting',
			value: null,
			isSuccess: false,
			initValue: 5,
		},
		anthropology: {
			isEditable: false,
			name: 'Anthropology',
			value: null,
			isSuccess: false,
			initValue: 1,
		},
		appraise: { isEditable: false, name: 'Appraise', value: null, isSuccess: false, initValue: 5 },
		archaeology: {
			isEditable: false,
			name: 'Archaeology',
			value: null,
			isSuccess: false,
			initValue: 1,
		},
		art: { isEditable: false, name: 'Art', value: null, isSuccess: false, initValue: 5 },
		charm: { isEditable: false, name: 'Charm', value: null, isSuccess: false, initValue: 15 },
		climb: { isEditable: false, name: 'Climb', value: null, isSuccess: false, initValue: 20 },
		creditRating: {
			isEditable: false,
			name: 'Credit Rating',
			value: null,
			isSuccess: false,
			initValue: 0,
		},
		cthulhuMythos: {
			isEditable: false,
			name: 'Cthulhu Mythos',
			value: null,
			isSuccess: false,
			initValue: 0,
		},
		disguise: { isEditable: false, name: 'Disguise', value: null, isSuccess: false, initValue: 5 },
		dodge: { isEditable: false, name: 'Dodge', value: null, isSuccess: false, initValue: 0 },
		driveAuto: {
			isEditable: false,
			name: 'Drive Auto',
			value: null,
			isSuccess: false,
			initValue: 20,
		},
		electricalRepair: {
			isEditable: false,
			name: 'Electrical Repair',
			value: null,
			isSuccess: false,
			initValue: 10,
		},
		fastTalk: { isEditable: false, name: 'Fast Talk', value: null, isSuccess: false, initValue: 5 },
		fightingBrawl: {
			isEditable: false,
			name: 'Fighting (Brawl)',
			value: null,
			isSuccess: false,
			initValue: 25,
		},
		firearmsHandgun: {
			isEditable: false,
			name: 'Firearms (Handgun)',
			value: null,
			isSuccess: false,
			initValue: 20,
		},
		firearmsRifle: {
			isEditable: false,
			name: 'Firearms (Rifle/Shotgun)',
			value: null,
			isSuccess: false,
			initValue: 25,
		},
		firstAid: {
			isEditable: false,
			name: 'First Aid',
			value: null,
			isSuccess: false,
			initValue: 30,
		},
		history: { isEditable: false, name: 'History', value: null, isSuccess: false, initValue: 5 },
		intimidate: {
			isEditable: false,
			name: 'Intimidate',
			value: null,
			isSuccess: false,
			initValue: 15,
		},
		jump: { isEditable: false, name: 'Jump', value: null, isSuccess: false, initValue: 20 },
		languageOwn: {
			isEditable: false,
			name: 'Language (Own)',
			value: null,
			isSuccess: false,
			initValue: 0,
		},
		languageOther: {
			isEditable: false,
			name: 'Language (Other)',
			value: null,
			isSuccess: false,
			initValue: 1,
		},
		law: { isEditable: false, name: 'Law', value: null, isSuccess: false, initValue: 5 },
		libraryUse: {
			isEditable: false,
			name: 'Library Use',
			value: null,
			isSuccess: false,
			initValue: 20,
		},
		listen: { isEditable: false, name: 'Listen', value: null, isSuccess: false, initValue: 20 },
		locksmith: {
			isEditable: false,
			name: 'Locksmith',
			value: null,
			isSuccess: false,
			initValue: 1,
		},
		mechanicalRepair: {
			isEditable: false,
			name: 'Mechanical Repair',
			value: null,
			isSuccess: false,
			initValue: 10,
		},
		medicine: { isEditable: false, name: 'Medicine', value: null, isSuccess: false, initValue: 1 },
		naturalWorld: {
			isEditable: false,
			name: 'Natural World',
			value: null,
			isSuccess: false,
			initValue: 10,
		},
		navigate: { isEditable: false, name: 'Navigate', value: null, isSuccess: false, initValue: 10 },
		occult: { isEditable: false, name: 'Occult', value: null, isSuccess: false, initValue: 5 },
		operateHeavyMachinery: {
			isEditable: false,
			name: 'Op. Hv. Machine',
			value: null,
			isSuccess: false,
			initValue: 1,
		},
		persuade: { isEditable: false, name: 'Persuade', value: null, isSuccess: false, initValue: 10 },
		pilot: { isEditable: false, name: 'Pilot', value: null, isSuccess: false, initValue: 1 },
		psychoanalysis: {
			isEditable: false,
			name: 'Psychoanalysis',
			value: null,
			isSuccess: false,
			initValue: 1,
		},
		psychology: {
			isEditable: false,
			name: 'Psychology',
			value: null,
			isSuccess: false,
			initValue: 10,
		},
		ride: { isEditable: false, name: 'Ride', value: null, isSuccess: false, initValue: 5 },
		science: { isEditable: false, name: 'Science', value: null, isSuccess: false, initValue: 1 },
		sleightOfHand: {
			isEditable: false,
			name: 'Sleight of Hand',
			value: null,
			isSuccess: false,
			initValue: 10,
		},
		spotHidden: {
			isEditable: false,
			name: 'Spot Hidden',
			value: null,
			isSuccess: false,
			initValue: 25,
		},
		stealth: { isEditable: false, name: 'Stealth', value: null, isSuccess: false, initValue: 20 },
		survival: { isEditable: false, name: 'Survival', value: null, isSuccess: false, initValue: 10 },
		swim: { isEditable: false, name: 'Swim', value: null, isSuccess: false, initValue: 20 },
		throw: { isEditable: false, name: 'Throw', value: null, isSuccess: false, initValue: 20 },
		track: { isEditable: false, name: 'Track', value: null, isSuccess: false, initValue: 10 },
	},
	weapons: [
		{
			name: 'unarmed',
			isEditable: false,
			skill: null,
			damage: '1d3+db',
			range: null,
			numberOfAttacks: 1,
			ammo: null,
			malfunction: false,
		},
	],
	combat: {
		damageBonus: null,
		build: null,
	},
	myStory: '',
	backstory: {
		personalDescription: '',
		traits: '',
		ideologyAndBeliefs: '',
		injuriesAndScars: '',
		significantPeople: '',
		phobiasAndManias: '',
		meaningfulLocations: '',
		arcaneTomesSpellsAndArtifacts: '',
		treasuredPossessions: '',
		encountersWithStrangeEntities: '',
	},
	gearAndPossessions: '',
	wealth: {
		spendingLevel: '',
		cash: '',
		assets: '',
	},
	fellowInvestigators: [],
	note: '',
}
